### PR TITLE
Update to MATSim 2025

### PR DESCRIPTION
**Pull request by sebhoerl**
Since April 2024 the release is called MATSim 2025

### CODE REVIEW

**Comment by Nitnelav** [comment]
Mmmm I don't find any branch/PR related to Matsim 16 in matsim-libs... Why 16 ?

**Comment by sebhoerl** [comment]
16 is the current development version (see matsim-libs pom.xml)

**Comment by Nitnelav** [comment]
ah yes of course. Do you want to skip the matsim 15 update and go straight for the 16 ?

**Comment by sebhoerl** [comment]
No, step by step. I would keep at matsim-15 branch and try to keep develop a bit up to date with recent versions of MATSim 16

**Pull request merged**
