### PR TITLE
Update to MATSim 15

### LINKED ISSUE #158: Update JDK
We should update the JDK version, otherwise we'll have problems with newer releases:
https://github.com/eqasim-org/ile-de-france/issues/157

I guess we have to do this anyways when we want to upgrade to a newer MATSim (#155)

### PR DESCRIPTION
**Pull request by sebhoerl**
Update to MATSim 15
- Fixes #158.
- Mainly updating imports

### CODE REVIEW

**Comment by sebhoerl** [comment]
Fixes #158.

**Comment by sebhoerl** [comment]
@Nitnelav Could you please check `RunComputeEmissionsEvents`? There is still the comment about MATSim 14, which should be resolved I think? And there is one line which I don't know how to update:
```java
emissionsConfig.setHbefaRoadTypeSource(EmissionsConfigGroup.HbefaRoadTypeSource.fromLinkAttributes);
```
Could you pelase have a look?

**Comment by Nitnelav** [comment]
Yes i'll check, this week is quite busy though. So probably next week.
Should we do like last time, I create a PR on https://github.com/eqasim-org/eqasim-java/tree/matsim-15 ?

**Comment by sebhoerl** [comment]
Ok great, thanks! Either that, or I also just added you to the project, so you should be able to add commits here directly.

**Comment by Nitnelav** [comment]
> @Nitnelav Could you please check `RunComputeEmissionsEvents`? There is still the comment about MATSim 14, which should be resolved I think? And there is one line which I don't know how to update:
> 
> ```java
> emissionsConfig.setHbefaRoadTypeSource(EmissionsConfigGroup.HbefaRoadTypeSource.fromLinkAttributes);
> ```
> 
> Could you please have a look?

FYI the method was deprecated and removed in matsim 15, the behavior is hard coded as 'fromLinkAttribute' now

**Comment by sebhoerl** [comment]
@Nitnelav Ok I see, so it is `OsmHbefaMapping` that is used by default? But do we have the attributes that are used there in the network (`type`, `allowed_speed`)? I think in our pt2matsim-generated networks the osm highway attribute is called differently and I'm not sure if we even have `allowed_speed`? Or am I missing something? Maybe would be good to have an integration test for that (in the `examples` package is probably the easiest).

**Comment by Nitnelav** [comment]
Yes i need to check that. Maybe the type was never taken into account 😬
But maybe it is a matsim 15 change...

And I agree, a test is needed here, I'll try to write something. 

And I think the code could be place in the core package, since it is not related to IdF no ?

**Comment by sebhoerl** [comment]
For the moment, the best would be if you take a look in examples, there we have the Corsica test scenario. But we're currently replacing this with a very small Melun scenario, so it might be worth waiting. And yes, might make sense to move it to core in some way, but I would leave it here for the time being. Step by step :)

**Comment by Nitnelav** [comment]
Ok I wrote the test. It takes a while but it works. I had to fetch some HBEFA sample csv from matsim-examples to make it work. I found a few bugs/improvements on the way also

**Comment by sebhoerl** [comment]
thanks! we'll merge a couple of other things before we merge the matsim 15 PR

**Comment by Nitnelav** [comment]
Yes ! I should update the CHANGELOG and some README also
By the way, just a thought, there is a lot of undocumented tools everywhere, we should write something somewhere listing the various commandline tools and what thery do

**Comment by Nitnelav** [comment]
Everything is fine here now, should we merge @sebhoerl ?

**Comment by sebhoerl** [comment]
Running the pipeline with the latest commit to check compatibility right now.

**Pull request merged**
